<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>magma</string>
		<string>mag</string>
	</array>
	<key>name</key>
	<string>Magma</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#block</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>angles</key>
		<dict>
			<key>begin</key>
			<string>&lt;</string>
			<key>end</key>
			<string>&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#set_builder_expression</string>
				</dict>
			</array>
		</dict>
		<key>any_type</key>
		<dict>
			<key>match</key>
			<string>\.</string>
			<key>name</key>
			<string>entity.name.class.magma</string>
		</dict>
		<key>arithmetic_operator</key>
		<dict>
			<key>comment</key>
			<string>Arithmetic operators</string>
			<key>match</key>
			<string>\+|-|/|\*|\^</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.magma</string>
		</dict>
		<key>arrow</key>
		<dict>
			<key>match</key>
			<string>-&gt;|:-&gt;</string>
		</dict>
		<key>assignment_statement</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.magma</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.magma</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Assignment statement</string>
			<key>match</key>
			<string>([_A-Za-z][\[\]_A-Za-z0-9,&lt;&gt;\s`]*?)?\s*((\b(div|cat|meet|join|mod|or|and)|(\+|-|/|\*|^)|)(:=))</string>
		</dict>
		<key>block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#printf_statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#declare_type_statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#declare_attributes_statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#for_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#control_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#end_function_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#intrinsic_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#other_statement_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#assignment_statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>block_comment</key>
		<dict>
			<key>begin</key>
			<string>\/\*</string>
			<key>comment</key>
			<string>Block comments</string>
			<key>end</key>
			<string>\*\/</string>
			<key>name</key>
			<string>comment.block.magma</string>
		</dict>
		<key>braces</key>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#set_builder_expression</string>
				</dict>
			</array>
		</dict>
		<key>brackets</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#set_builder_expression</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#line_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_comment</string>
				</dict>
			</array>
		</dict>
		<key>comparison_operator_keyword</key>
		<dict>
			<key>comment</key>
			<string>Comparison operator keywords</string>
			<key>match</key>
			<string>\b(le|lt|ge|gt|eq|ne|cmpeq|cmpne|in|notin|subset|notsubset)\b</string>
			<key>name</key>
			<string>keyword.operator.comparison.magma</string>
		</dict>
		<key>constant</key>
		<dict>
			<key>comment</key>
			<string>Constants</string>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.word_like.magma</string>
		</dict>
		<key>constructor</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constructor_bits</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#record_constructor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#func_constructor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#other_constructor</string>
				</dict>
			</array>
		</dict>
		<key>constructor_bits</key>
		<dict>
			<key>match</key>
			<string>-&gt;|:-&gt;</string>
		</dict>
		<key>control_keyword</key>
		<dict>
			<key>comment</key>
			<string>Control keywords</string>
			<key>match</key>
			<string>\b(if|end\s+if|else|elif|then|for|while|end\s+for|end\s+while|do|return|break|continue|raise|assert|assert2|assert3|try|end\s+try|catch|require|requirerange|requirege|error|repeat|until|case|when|end\s+case|default)\b</string>
			<key>name</key>
			<string>keyword.control.magma</string>
		</dict>
		<key>declare_attributes_statement</key>
		<dict>
			<key>begin</key>
			<string>(\bdeclare\s+attributes)\s+([_A-Za-z][_A-Za-z0-9]*)(\s*\[\s*([_A-Za-z][_A-Za-z0-9]*)\s*\])?\s*:</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.magma</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.magma</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.magma</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b[_A-Za-z][_A-Za-z0-9]*\b</string>
					<key>name</key>
					<string>variable.parameter.magma</string>
				</dict>
			</array>
		</dict>
		<key>declare_type_statement</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\bdeclare\s+type)\s+([_A-Za-z][_A-Za-z0-9]*)(\s*\[\s*([_A-Za-z][_A-Za-z0-9]*)\s*\])?\s*:</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.magma</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.magma</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.magma</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Version with inheritances</string>
					<key>end</key>
					<string>;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b[_A-Za-z][_A-Za-z0-9]*\b</string>
							<key>name</key>
							<string>entity.name.class.magma</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.magma</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.magma</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.magma</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Simple version</string>
					<key>match</key>
					<string>(\bdeclare\s+type)\s+([_A-Za-z][_A-Za-z0-9]*)(\s*\[\s*([_A-Za-z][_A-Za-z0-9]*)\s*\])?</string>
				</dict>
			</array>
		</dict>
		<key>end_function_keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.magma</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.magma</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>End function definition keywords</string>
			<key>match</key>
			<string>\b(end\s+)(function|procedure|intrinsic)\b</string>
		</dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arrow</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constructor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#other_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression_group</string>
				</dict>
			</array>
		</dict>
		<key>expression_group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function_call</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#indexed_set</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#multi_set</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parens</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#brackets</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#braces</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#angles</string>
				</dict>
			</array>
		</dict>
		<key>for_keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.magma</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.magma</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.magma</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Keyword "for"</string>
			<key>match</key>
			<string>\b(for)\s+([_A-Za-z][_A-Za-z0-9]*)\s+(in)\b</string>
		</dict>
		<key>func_constructor</key>
		<dict>
			<key>begin</key>
			<string>\b(func|proc)\s*&lt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.magma</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\|</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[_A-Za-z][_A-Za-z0-9]*</string>
					<key>name</key>
					<string>variable.parameter.magma</string>
				</dict>
			</array>
		</dict>
		<key>function_call</key>
		<dict>
			<key>begin</key>
			<string>[_A-Za-z][_A-Za-z0-9]*\s*\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.function-call.magma</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function_call_params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>function_call_params</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.magma</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([_A-Za-z][_A-Za-z0-9]*)\s*(:=)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.other.magma</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.magma</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(~)\s*([_A-Za-z][_A-Za-z0-9]*)</string>
				</dict>
			</array>
		</dict>
		<key>function_keyword</key>
		<dict>
			<key>begin</key>
			<string>\b(function|procedure)\b\s*([_A-Za-z][_A-Za-z0-9]*)?\b\s*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.magma</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.magma</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function definition keywords</string>
			<key>end</key>
			<string>(?!\s*(\())(?=.)\s*</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function_params</string>
				</dict>
			</array>
		</dict>
		<key>function_params</key>
		<dict>
			<key>begin</key>
			<string>\(\s*</string>
			<key>end</key>
			<string>\)\s*</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#paramname</string>
				</dict>
			</array>
		</dict>
		<key>indexed_set</key>
		<dict>
			<key>begin</key>
			<string>{@</string>
			<key>end</key>
			<string>@}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#set_builder_expression</string>
				</dict>
			</array>
		</dict>
		<key>integer_literal</key>
		<dict>
			<key>comment</key>
			<string>Numbers</string>
			<key>match</key>
			<string>\b([0-9]+|[0-9]+\.[0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric.magma</string>
		</dict>
		<key>intrinsic_docstring</key>
		<dict>
			<key>begin</key>
			<string>{\s*</string>
			<key>end</key>
			<string>}\s*</string>
			<key>name</key>
			<string>comment.block.documentation.magma</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<key>intrinsic_keyword</key>
		<dict>
			<key>begin</key>
			<string>\b(intrinsic)\s+([_A-Za-z][_A-Za-z0-9]*)\b\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.magma</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.magma</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>intrinsics</string>
			<key>end</key>
			<string>(?!\s*(\(|{|-&gt;|:))(?=.)\s*</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#intrinsic_params_return_docstring</string>
				</dict>
			</array>
		</dict>
		<key>intrinsic_optparam</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.magma</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([_A-Za-z][_A-Za-z0-9]*)\s*:=</string>
		</dict>
		<key>intrinsic_optparams</key>
		<dict>
			<key>begin</key>
			<string>:\s*</string>
			<key>end</key>
			<string>\)\s*</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#intrinsic_optparam</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>intrinsic_params</key>
		<dict>
			<key>begin</key>
			<string>\(\s*</string>
			<key>end</key>
			<string>\)\s*|(?=:)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#intrinsic_paramtype</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#intrinsic_parens</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#paramname</string>
				</dict>
			</array>
		</dict>
		<key>intrinsic_params_return_docstring</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#intrinsic_params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#intrinsic_optparams</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#intrinsic_returntypes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#intrinsic_docstring</string>
				</dict>
			</array>
		</dict>
		<key>intrinsic_paramtype</key>
		<dict>
			<key>begin</key>
			<string>(\b[_A-Za-z][_A-Za-z0-9]*)?\s*::\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.magma</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\s*([_A-Za-z]|\[|{|\.|&lt;))(?=.)\s*</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
			</array>
		</dict>
		<key>intrinsic_parens</key>
		<dict>
			<key>begin</key>
			<string>\(\s*</string>
			<key>end</key>
			<string>\)\s*</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#intrinsic_parens</string>
				</dict>
			</array>
		</dict>
		<key>intrinsic_returntypes</key>
		<dict>
			<key>begin</key>
			<string>(?=-&gt;\s*)</string>
			<key>end</key>
			<string>(?!\s*(-&gt;|,))(?=.)\s*</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.magma</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*(-&gt;|,)\s*([_A-Za-z][_A-Za-z0-9]*)</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s*(-&gt;|,)\s*(\[\]|{}|{\[\]}|{@@}|{\*\*}|&lt;&gt;)</string>
				</dict>
			</array>
		</dict>
		<key>iset_type</key>
		<dict>
			<key>begin</key>
			<string>{@</string>
			<key>end</key>
			<string>@}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
			</array>
		</dict>
		<key>line_comment</key>
		<dict>
			<key>comment</key>
			<string>Line comments</string>
			<key>match</key>
			<string>\/\/.*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.magma</string>
		</dict>
		<key>literal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#integer_literal</string>
				</dict>
			</array>
		</dict>
		<key>logical_operator_keyword</key>
		<dict>
			<key>comment</key>
			<string>Logical operator keywords</string>
			<key>match</key>
			<string>\b(and|not|or)\b</string>
			<key>name</key>
			<string>keyword.operator.bool.logical.magma</string>
		</dict>
		<key>mset_type</key>
		<dict>
			<key>begin</key>
			<string>{\*</string>
			<key>end</key>
			<string>\*}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
			</array>
		</dict>
		<key>multi_set</key>
		<dict>
			<key>begin</key>
			<string>{\*</string>
			<key>end</key>
			<string>\*}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#set_builder_expression</string>
				</dict>
			</array>
		</dict>
		<key>operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#operator_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arithmetic_operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#other_operator</string>
				</dict>
			</array>
		</dict>
		<key>operator_keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#logical_operator_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comparison_operator_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#other_operator_keyword</string>
				</dict>
			</array>
		</dict>
		<key>other_constructor</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.magma</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Constructors</string>
			<key>match</key>
			<string>\b([_A-Za-z]+)&lt;</string>
		</dict>
		<key>other_keyword</key>
		<dict>
			<key>comment</key>
			<string>Other keywords</string>
			<key>match</key>
			<string>\b(exists|forall|rep|random|select|else|where|is|by|Self|assigned)\b</string>
			<key>name</key>
			<string>keyword.other.magma</string>
		</dict>
		<key>other_operator</key>
		<dict>
			<key>comment</key>
			<string>Other operators</string>
			<key>match</key>
			<string>#|&amp;|`|!|@|@@|\.|\.\.|\.\.\.|~</string>
			<key>name</key>
			<string>keyword.operator.other.magma</string>
		</dict>
		<key>other_operator_keyword</key>
		<dict>
			<key>comment</key>
			<string>Other operator keywords</string>
			<key>match</key>
			<string>\b(div|cat|meet|join|diff|sdiff|mod)\b</string>
			<key>name</key>
			<string>keyword.operator.other.magma</string>
		</dict>
		<key>other_statement_keyword</key>
		<dict>
			<key>comment</key>
			<string>Other statement-level keywords</string>
			<key>match</key>
			<string>\b(load|print|printf|fprintf|vprint|vprintf|delete|freeze|quit|exit|import|declare|type|attributes|time|vtime)\b</string>
			<key>name</key>
			<string>keyword.other.magma</string>
		</dict>
		<key>paramname</key>
		<dict>
			<key>match</key>
			<string>[_A-Za-z][_A-Za-z0-9]*</string>
			<key>name</key>
			<string>variable.parameter.magma</string>
		</dict>
		<key>parens</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>printf_statement</key>
		<dict>
			<key>begin</key>
			<string>\b((f?printf)|(Sprintf\()|((vprintf)\b.*:))\s*(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.magma</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.other.magma</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.magma</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.magma</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.magma</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(%([-]?[0-9]*(\.[0-9]*)?|\*)[oOmh])|(%%)</string>
					<key>name</key>
					<string>constant.character.escape.magma</string>
				</dict>
				<dict>
					<key>match</key>
					<string>%</string>
					<key>name</key>
					<string>invalid.illegal.magma</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^"\\%]</string>
					<key>name</key>
					<string>string.quoted.double.magma</string>
				</dict>
			</array>
		</dict>
		<key>record_constructor</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.magma</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.magma</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(rec)\s*&lt;\s*([_A-Za-z][_A-Za-z0-9]*)\b</string>
		</dict>
		<key>sequence_type</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
			</array>
		</dict>
		<key>set_builder_expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#set_builder_quantifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>set_builder_quantifier</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.magma</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.magma</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[:,]\s*([_A-Za-z][_A-Za-z0-9]*)\s+(in)\b</string>
		</dict>
		<key>set_type</key>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
			</array>
		</dict>
		<key>setseq_type</key>
		<dict>
			<key>begin</key>
			<string>{\[</string>
			<key>end</key>
			<string>\]}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
			</array>
		</dict>
		<key>simple_type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([_A-Za-z][_A-Za-z0-9]*)\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.magma</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>[_A-Za-z][_A-Za-z0-9]*</string>
					<key>name</key>
					<string>entity.name.class.magma</string>
				</dict>
			</array>
		</dict>
		<key>string_literal</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>Strings</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.magma</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.magma</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^"\\]</string>
				</dict>
			</array>
		</dict>
		<key>tuple_type</key>
		<dict>
			<key>begin</key>
			<string>&lt;</string>
			<key>end</key>
			<string>&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
			</array>
		</dict>
		<key>type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#any_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#simple_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sequence_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#set_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#setseq_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#iset_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mset_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tuple_type</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.magma</string>
	<key>uuid</key>
	<string>86b1670b-7756-4792-bdd1-1392d39d26a4</string>
</dict>
</plist>
